name: firm-transaction-network
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyterlab
  - numpy == 1.24.3
  - matplotlib == 3.10.6
  - geopandas == 1.1.1
  - seaborn == 0.13.2

  - pip:
      - gdown == 5.2.0
      - pyyaml == 6.0.2
      - python-igraph
      - leidenalg
      - infomap
      - nbstripout
